### ISSUE TITLE
部署文档

### ISSUE THREAD

**Issue by WeihanLi** [WeihanLi/ActivityReservation#7]

**Comment by WeihanLi** [comment]
- [ ] Standalone 单机版
- [ ] Cluster 集群版

**Comment by ghd258** [comment]
可以写个详细的部署步骤吗

**Comment by WeihanLi** [comment]
> 可以写个详细的部署步骤吗

单机版的话可以直接用[单机版部署文档](https://github.com/WeihanLi/ActivityReservation/blob/dev/docs/deploy/standalone.md)来部署，推荐使用 docker 来部署，如果想自定义一些配置的话可以改源码，重新打包 docker 镜像

集群版文档还没梳理好，打算使用 helm v3 来部署，目前的话也有相应资源的 yaml 配置，可以直接使用 kubectl 来部署到 k8s 上

下面是我现在在用的部署脚本（打算迁移使用 helm v3 来部署，v3还没发布正式版，angular的客户端已经支持 https://developer.aliyun.com/hub/detail?name=reservation-client&version=1.0.0# ）：

> kubectl apply -f https://raw.githubusercontent.com/WeihanLi/ActivityReservation/dev/redis.yaml
kubectl apply -f https://raw.githubusercontent.com/WeihanLi/ActivityReservation/dev/elasticsearch.yaml -f https://raw.githubusercontent.com/WeihanLi/ActivityReservation/dev/kibana.yaml
kubectl apply -f /home/pipeline/k8s/configMap.yml
kubectl apply -f https://raw.githubusercontent.com/WeihanLi/ActivityReservation/dev/reservation-deployment.yaml -f https://raw.githubusercontent.com/WeihanLi/ActivityReservation/dev/ActivityReservation.Clients/ReservationClient/k8s-deploy.yaml

configMap 是我自己加的，没有在代码库里，主要用来保存数据库连接字符串等敏感信息了，示例如下:

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-configs
  namespace: default
data:
  appsettings: |
    {      
      "ConnectionStrings": {
        "Redis": "redis-server",
        "Reservation": "Server=tcp:weihanli.database.windows.net,1433;Initial Catalog=reservation;Persist Security Info=False;User ID=liweihan;Password=@Admin888;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=300;",
        "ElasticSearch": "http://elasticsearch:9200"
      },
      "MpWechat":{
        "AppId": "x",
        "AppSecret": "x",
        "Token": "x",
        "AESKey": "x"
      },
      "WxApp":{
        "AppId": "x",
        "AppSecret": "x",
        "Token": "x",
        "AESKey": "x"
      },
      "AppSettings": {
        "WechatSubscribeReply": "",
        "SentryClientKey": "xx"
      },
      "Tencent": {
        "Captcha": {
          "AppId": "2062135016",
          "AppSecret": "xxx**"
        }
      },
      "Storage":{
        "Gitee":{
          "UserName": "weihanli",
          "RepositoryName": "storage",
          "AccessToken": "xxx"
        }
      },
      "GoogleRecaptcha": {
        "SiteKey": "xxx",
        "Secret": "xxx"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Warning",
          "ActivityReservation": "Debug",
          "RequestLog": "Debug",
          "PerformanceLog": "Debug"
        }
      }
    }
```
